# Generated by Django 4.2.7 on 2023-12-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Назва')),
                ('anons', models.CharField(max_length=260, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Текст')),
                ('data', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
